### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TomWq** [react-native-oh-library/react-native-geolocation#7]
源码内 harmony/geolocation/oh-package.json5  里  "name": "@react-native-oh-tpl/react-native-geolocation"
但是文档里写的是@react-native-oh-tpl/geolocation 导致引入会失败

**Comment by wangzhi17** [comment]
我的也是

**Comment by wangzhi17** [comment]
文档写的有问题，package.json 里面是@react-native-oh-tpl/react-native-geolocation:"",
oh-package.json5改成 "@react-native-oh-tpl/geolocation": "file:../../node_modules/@react-native-oh-tpl/react-native-geolocation/harmony/geolocation.har"

**Comment by dw18829031738** [comment]
https://github.com/react-native-oh-library/react-native-geolocation/issues/12 已修改
